site_name: lz-feeds
site_description: 每日信息摘要
docs_dir: docs

theme:
  name: material
  language: zh
  features:
    - navigation.instant
    - navigation.top
  palette:
    scheme: default
    primary: indigo

plugins:
  - search

markdown_extensions:
  - tables
  - meta
